version: "3"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=inception
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: ["postgres", "-c", "log_statement=all"]